### ISSUE TITLE
Any plan to support 4.26?

### ISSUE THREAD

**Issue by WuAlan** [DaedalicEntertainment/ue4-test-automation#13]
Hi, thanks to share this fancy automation framework. I am trying to use this in the new version of unreal by source code (4.26), but meets some problems, any plans to support?
1. Has a compiler error at:
    FActorSpawnParameters SpawnInfo;
    SpawnInfo.Instigator = Instigator;
2.When run by Automation window, the cases never stopped after success..

other: The GPU version becomes to a array of float[4] in 4.26, I just make simple change to only  read the first one...(runs ok..)

**Comment by comerford** [comment]
@WuAlan - I've submitted a PR that fixed the compilation error here: 

https://github.com/DaedalicEntertainment/ue4-test-automation/pull/15

I haven't tried with 4.26 yet

**Comment by WuAlan** [comment]
> @WuAlan - I've submitted a PR that fixed the compilation error here:
> 
> #15
> 
> I haven't tried with 4.26 yet

Thanks, I tried on the change, it works on 4.26.
